version: '3'

services:
  device:
    build: .
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - DEVICE_ID=${DEVICE_ID:-RASPI_AUTO}
    restart: unless-stopped
    networks:
      - device-network

networks:
  device-network:
    driver: bridge 