version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: centralsrt
    command: >
      sh -c "
        echo 'Waiting for MySQL to be ready...' &&
        while ! nc -z db 3306; do
          sleep 1
        done &&
        echo 'MySQL is ready!' &&
        npx prisma generate &&
        npx prisma db push --accept-data-loss &&
        if [ "$NODE_ENV" = "production" ]; then
          npm run build && npm run start
        else
          npm run dev
        fi
      "
    ports:
      - '3001:3000'
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - DATABASE_URL=mysql://root:1122@db:3306/dbcentral
      - NODE_ENV=${NODE_ENV:-development}
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1122
      - MYSQL_DATABASE=dbcentral
    ports:
      - '3307:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
